spring:
   session:
      store-type:   redis
      redis:
         namespace: springback:session
   redis:
      host:   127.0.0.1 
      port:   6379
      
server:
   servlet:
      session:
         timeout: 30m
         
session-check-exclusion: /doLogin, /login

         

         